# Generated by Django 4.2.2 on 2023-06-27 20:46

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=280, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=280, unique=True)),
                ('avatar', easy_thumbnails.fields.ThumbnailerImageField(default='djangochatserver/default.jpg', upload_to='djangochatserver')),
                ('mini_avatar', easy_thumbnails.fields.ThumbnailerImageField(default='djangochatserver/default_small.jpg', upload_to='djangochatserver')),
                ('online', models.BooleanField(default=False)),
                ('chatroom', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='messapp.chatroom')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=280)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messapp.profile')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messapp.chatroom')),
            ],
        ),
    ]
